version: "3.9"

services:
  db:
    image: postgres:16                 # versión estable a mayo‑2025
    container_name: dqgb_postgres      # un nombre fácil de reconocer
    restart: unless-stopped            # se reinicia si cierras sesión
    env_file:
      - .env                           # usaremos las variables que pondrás más abajo
    ports:
      - "5432:5432"                    # host:contenedor
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: dqgb_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  web:
    build: .
    container_name: dqgb_web
    restart: unless-stopped
    env_file: .env
    command: /app/entrypoint.sh
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  worker:
    build: .
    container_name: dqgb_worker
    restart: unless-stopped
    env_file: .env
    command: celery -A config worker --loglevel=info
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  beat:
    build: .
    container_name: dqgb_beat
    restart: unless-stopped
    env_file: .env
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

volumes:
  postgres_data:
  static_volume:
  media_volume:
                     # volumen nombrado para persistencia
