version: "3.9"

services:
  db:
    image: postgres:16                 # versión estable a mayo‑2025
    container_name: dqgb_postgres      # un nombre fácil de reconocer
    restart: unless-stopped            # se reinicia si cierras sesión
    env_file:
      - .env                           # usaremos las variables que pondrás más abajo
    ports:
      - "5432:5432"                    # host:contenedor
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:                       # volumen nombrado para persistencia
