# Generated by Django 5.0.4 on 2025-05-08 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='Editorial')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='ISBN‑10')),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN‑13')),
                ('genre', models.CharField(choices=[('FIC', 'Ficción'), ('NF', 'No Ficción'), ('SCI', 'Ciencia'), ('TEC', 'Tecnología'), ('BIO', 'Biografía'), ('HIS', 'Historia')], default='FIC', max_length=3, verbose_name='Género')),
                ('language', models.CharField(default='Español', max_length=30, verbose_name='Idioma')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Páginas')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='Portada')),
                ('copies_total', models.PositiveIntegerField(default=1, verbose_name='Ejemplares totales')),
                ('copies_available', models.PositiveIntegerField(default=1, verbose_name='Ejemplares disponibles')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio (MXN)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['title'],
            },
        ),
    ]
