# Generated by Django 5.0.4 on 2025-05-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('PHYS', 'Físico'), ('EBOOK', 'E‑book'), ('AUDIO', 'Audiolibro')], default='PHYS', max_length=5, verbose_name='Tipo de libro'),
        ),
    ]
